project_id = "zvuwkffneqxqsihlnfsd"

[api]
enabled = true

[functions.github-sync]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.prompt-wizard]
verify_jwt = false

[functions.suggest-metadata]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.ensure-token-allowance]
verify_jwt = false

[functions.suggest-skill-metadata]
verify_jwt = false

[functions.refine-prompt]
verify_jwt = false

[functions.delete-my-account]
verify_jwt = false

[functions.suggest-workflow-metadata]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false

[functions.blog-api]
verify_jwt = false

[functions.api]
verify_jwt = false

[functions.fetch-skill-md]
verify_jwt = false

[functions.notify-admin]
verify_jwt = false

[functions.suggest-claw-metadata]
verify_jwt = false

[functions.canvas-ai]
verify_jwt = false
